//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProyectoWebFinal.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class evento
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public evento()
        {
            this.estadisticas_evento = new HashSet<estadisticas_evento>();
            this.inventario = new HashSet<inventario>();
            this.puntuacion_evento = new HashSet<puntuacion_evento>();
            this.cliente = new HashSet<cliente>();
        }
    
        public int id_evento { get; set; }
        public string nombre { get; set; }
        public int id_tipo { get; set; }
        public int id_lugar { get; set; }
        public string descripcion { get; set; }
        public System.DateTime fecha { get; set; }
        public int codigo_tra { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<estadisticas_evento> estadisticas_evento { get; set; }
        public virtual trabajador trabajador { get; set; }
        public virtual lugar lugar { get; set; }
        public virtual tipo tipo { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<inventario> inventario { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<puntuacion_evento> puntuacion_evento { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<cliente> cliente { get; set; }
    }
}
