//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProyectoWebFinal.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class proyectowebEntities : DbContext
    {
        public proyectowebEntities()
            : base("name=proyectowebEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<cliente> cliente { get; set; }
        public virtual DbSet<estadisticas_evento> estadisticas_evento { get; set; }
        public virtual DbSet<evento> evento { get; set; }
        public virtual DbSet<inventario> inventario { get; set; }
        public virtual DbSet<lugar> lugar { get; set; }
        public virtual DbSet<puntuacion_evento> puntuacion_evento { get; set; }
        public virtual DbSet<rol> rol { get; set; }
        public virtual DbSet<tel_cliente> tel_cliente { get; set; }
        public virtual DbSet<tel_trabajador> tel_trabajador { get; set; }
        public virtual DbSet<tipo> tipo { get; set; }
        public virtual DbSet<trabajador> trabajador { get; set; }
        public virtual DbSet<usuario> usuario { get; set; }
    }
}
