//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProyectoWebFinal.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class usuario
    {
        public int id_usuario { get; set; }
        public string nombre_usuario { get; set; }
        public int id_rol { get; set; }
        public int codigo_tra { get; set; }
        public int cedula_cli { get; set; }
    
        public virtual cliente cliente { get; set; }
        public virtual rol rol { get; set; }
        public virtual trabajador trabajador { get; set; }
    }
}
